services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # REST API + Web UI (Dashboard)
      #- "6334:6334"   # gRPC (tùy chọn)
    volumes:
      - ../qdrant-data:/qdrant/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - n8n-net

networks:
  n8n-net:
    driver: bridge
